.gitignore
fixed #95 
現状だと`minishell`が生成されているとgitの追跡対象になってしまうので、
`.gitignore`にminishellを追加して対象外にしました。
=> ignore minishell binary

Makefile, inc/minish_signal.h, src/main.c, src/minish_signal.c
fix #18, fix #19, fix #20, fix #21
signal関連の対応を`signal[.c|.h]`というファイルに実装しました。
次のことをできるようにしています。
- `ctrl+c`: 新しい行に切り替えます。
- `ctrl+\`: 何もしないようにしています。
なお、`ctrl+d`についてはmain側でEOFを感知した場合に抜けることで対応しています。
（後々なにか対応が必要になるかも？）
=> signalの対応を追加しました。

src/main.c
fixed #104, fixed #101
履歴を登録するとき、空文字の場合は履歴を追加しないように対応しました。
=> 空文字の場合履歴を追加しないように修正

test.mk
fixed #120 
ビルトインのテスト用Makefileを`test.mk`という名前のファイルにひとまとめにしました。
以降はtest_<cmd>.cがbuiltin/以下に存在することを前提に
SRCに対象のコマンドのソースコードを追加することで対応できます。
=> #120 ビルトインのテスト用Makefileを一つに統合

inc/cmd.h
fixed #111 
cmdの構造体にリダイレクトの種類を判定するためのenum変数を追加しました。
字句解析での判定で利用する予定です。
=> リダイレクトのタイプをenumで追加

src/builtin/env.c, test.mk, tests/builtin/test_env.c
fix #28 
課題
プロトタイプを```int	builtin_env(int argc, char *argv[], char *envp[])```としており、main関数からenvpを受け渡す必要があります。（この実装はまだしていない。issueに追加します。）
対処
envpさえ渡せれば、envのオプション・引数なしとして十分に動作します。そのため、
main関数からbuilt-in系のコマンドへの繋がりがはっきりし、この実装が問題になった場合には再実装する方針を考えています。
=> add built-in env

inc/builtin.h, inc/struct.h, src/builtin/env.c, test.mk, tests/builtin/test_env.c
t_envにminishell独自のenvpの構造体もたせた。そのため、built-in envも修正する必要が合った。
=> fix char **envp to t_env

inc/env_utils.h, inc/struct.h, src/builtin/env.c, src/builtin/env_utils.c, src/builtin/env_utils_2.c, src/builtin/unset.c, src/initialize.c, tests/builtin/test_unset.c
fixed #141 
- t_env構造体にkeyを格納する変数を追加しました。
- それに伴い、env,unsetの挙動を修正しております。
- 変更に伴って未使用になった関数は削除しました。(env_utils.cのget_env_name())
あと、ダブルフリーを起きている箇所があったので修正してあります。
詳細はコメントにて
=> env構造体にkeyを追加、それを利用していた関数の修正

lib/libft/ft_memmove.c, lib/libft/ft_memset.c, lib/libft/ft_printf/srcs/ft_printf.c, lib/libft/ft_printf/srcs/ft_printf_utils1.c, lib/libft/ft_printf/srcs/ft_printf_utils2.c, lib/libft/ft_strlen_until.c, lib/libft/ft_strnlen.c, lib/libft/get_next_line/get_next_line.c, lib/libft/get_next_line/get_next_line_bonus.c, lib/libft/get_next_line/get_next_line_utils.c, lib/libft/get_next_line/get_next_line_utils_bonus.c, src/builtin/builtin_utils.c, src/builtin/echo.c, src/main.c, src/minish_signal.c, src/tokenizer/get_token_capa.c, src/tokenizer/is_quote_closed.c, src/tokenizer/is_redirect_validate.c, src/tokenizer/tokenizer.c
fixed #158 
norm対策で日本語で書かれていたコメントを英語に変更しました。
テストコードについては提出に含めない予定なので対応していません。
=> 日本語コメントの英語化

src/tokenizer/is_quote_closed.c, src/tokenizer/read_token.c, src/tokenizer/tokenizer.c
fixed #172, #10
もともとクオートで閉じられていなかった場合エラーを出力していましたが、
課題要件に合わせるためエラーを出さないように修正しました。
```sh
./test_tokenizer.out "echo \"hoge fuga\" he's cool!'hello world'!"
token[0]=echo
token[1]="hoge fuga"
token[2]=he
token[3]='s cool!'
token[4]=hello
token[5]=world
token[6]='!
```
=> クオート閉じてなくても通常の文字として扱う形に修正

inc/parser.h, src/parser/parser_utils.c, src/parser/setup_cmds.c, tests/parser/test_parser.c
fixed #89 
パーサーで$?が展開するように対応しました。
```sh
./test_parser.out "cat \"\$?\" \$?\$SHELL\$SHELL"
cmd->type=0
cmd->argc=3
cmd->argv=[cat,"0",0/bin/zsh/bin/zsh,NULL]
```
=> 終了ステータスを展開できるように変更

src/initialize.c
fixed #150 
メモリの開放処理を充実させました。
./minishellで動作確認しましたが、現状ではメモリリークは出てなさそうでした。
=> メモリ開放処理を充実させました。

.github/workflows/pr_check.yml, src/initialize.c
fixed #169
次のように修正しました。
- normの対象を提出物のみにしました。
- ビルドチェックを追加しました。
=> 対象を提出物のみにしぼり、ビルドチェックを追加

inc/builtin.h, inc/builtin_utils.h, inc/invoke_command.h, src/builtin/cd.c, src/builtin/echo.c, src/builtin/exit.c, src/builtin/pwd.c, src/invoke_cmd/exec_pipeline.c, src/invoke_cmd/invoke_command.c, src/invoke_cmd/pipeline_helper.c
ビルトインコマンドを実行可能にしました。
挙動はミニシェルで確認お願いします。
=> 191 invoke cmd handle built in command

Makefile, src/builtin/export_exec.c, src/initialize.c, tests/builtin/test_cd.c, tests/builtin/test_echo.c, tests/builtin/test_exit.c, tests/builtin/test_pwd.c
fixed #192.
```
export x
export x+=123
```
のようにしたときに追加できていなかったのですが、追加できるように対応しました。
=> keyのみの場合に+=で追加できるように修正

Makefile, inc/builtin_utils.h, inc/env_utils_2.h, src/builtin/env_utils_2.c, src/builtin/split_key_value.c, src/initialize.c
fixed #193 
`export a="abc"`のとき、`a=""abc""`になっていましたが
`a="abc"`とクオートが取れた状態で環境変数に入れるように修正しました。
シングルクオートでも同様に動作します。
`test_export.out`で確認可能です。
テスト確認用minishが起動しますので、export,envコマンドを利用してご確認ください。
=> split_key_value分離

Makefile, inc/parser.h, inc/parser_free.h, src/main.c, src/parser/allocate_cmds.c, src/parser/allocate_cmds_utils.c, src/parser/allocate_cmds_utils_2.c, src/parser/expand_tokens.c, src/parser/parser.c, src/parser/parser_free.c, src/parser/parser_utils.c, src/parser/setup_cmds.c
fixed #198 
メモリの確保が正しくできていなかったので、parserの内部処理を作り直しました。
インターフェース部分に変更はないのでinvoke_cmdはそのまま使えます。
メモリリークが発生していますが、
こちらの対応については #207 でまとめて行うので、ここでは残したままとさせてください。
=> argvのメモリ領域確保対応

src/tokenizer/read_token.c
fixed #213
tokenizerが元々`"a""b"`を`["a","b"]`別トークンで扱っていたのを`["\"a\"\b\""]`という形で一つのトークンにまとめる形にしました。
クオートをなくす処理についてはParserの責務ですので、このプルリクエストでは対応していません。
詳しくはｰ>#200
`make`後`./minish`で確認で動作可能ですが、効果を確認するのは難しいです。
一応対応前後でechoの挙動が変わります。
- 修正前: `echo "a""b" -> "a" "b"` ※token区切りでスペースを入れて出力しているため、修正前はスペースが入る
- 修正後: `echo "a""b" -> "a""b"`
=> tokenizerのquote処理見直し

inc/signal/minish_signal.h, src/invoke_cmd/exec_pipeline.c, src/invoke_cmd/invoke_command.c, src/invoke_cmd/wait_pipeline.c, src/minish_signal.c
外部コマンド実行中にシグナルを受け取った時の処理を追加しました。
`./minishell`で試してください。
=> add signal function

inc/common/struct.h, inc/main.h, src/main.c, src/minish_signal.c
fixed #222
プロセス実行中の最終ステータスは取得できていましたが、プロンプト入力中にステータスが取得できていませんでした。
今回の対応でプロンプト入力中にシグナルを受信した際にもexitステータスを取得するようになりました。
また今回の変更に伴って、グローバル変数を追加しています。
`./minish`でプロンプト入力中に`Ctrl+C`の後、`echo $?`で取得できているか確認できます。
=> プロンプト入力中にシグナルを受け取ると終了ステータスが更新されるようになる対応

inc/invoke_cmd/pipeline_helper.h, inc/invoke_cmd/redirect.h, src/invoke_cmd/invoke_command.c, src/invoke_cmd/redirect.c
fixed #225 
リダイレクト失敗時に結果の成否に関わらずビルトイン関数が実行される状態になっていましたので、
boolとして結果を返し、呼び出し元もそれにあわせて後続の処理を実行しないようにしました。
- `./minishell`実行後、下記の点についてご確認いただけたらと思います。
- `echo > <書き込み権限がないファイル>`で`minish: <file>: Permission denied`のみ表示されるか
- `echo $?`で1が表示されるか
- ビルトインの修正しか行っておりませんので、外部コマンドは別途対応が必要です。
=> リダイレクト失敗時にbuiltin関数を実行しないように修正

src/invoke_cmd/invoke_command.c
fix #232 
- 可読性が低かったので、リファクタリングしました。
- exec_unit_builtinでリダイレクトを２つまでしか処理できませんが、is_unit_builtinでは拡張性を考慮してリダイレクトが2つ以上合ってもtrueを返すようにしています。
以下のようなリダイレクトが２つまでのシンプルな処理は実行できるように修正しました。./minishellで検証お願いします。
`echo hello`
`echo hello > outfile`
`echo hello<< EOF > outfile`
=> fix redirect funcs

src/invoke_cmd/exec_pipeline.c
fix #230 
fix #227 
修正内容は口頭でお伝えした2行だけです。
no-permissionf-file等を作成して、./minishellで検証お願いいたします。
=> fix issue 230 and 227

src/parser/expand_env.c
fixed #231 
元々`echo $'SHELL'`のようなコマンドで無限ループになっていた件ですが、
`echo $`のような$のみでも同様に無限ループに陥ることが判明したので対応しました。
- minishell起動後`echo $`などで$だけ表示され、次のプロンプトが正常に入力できることを確認してください。
- `echo $'SHELL'`の場合`SHELL`と出るのがBash準拠なのですが、minishellだと`$SHELL`となります。
- こちらの対応についてはWANTとさせてください。
=> $のみの場合、無限ループにならないように修正

src/invoke_cmd/exec_pipeline.c, src/invoke_cmd/execute_cmd.c
許可されていない.shファイルを渡されたときにpermission deniedと出力されるように修正しました。
`./minishell`で試してもらいたいです。
期待通りか確認してほしいケース
- 外部コマンド　lsなど
- 実行許可がある.shファイル
- 実行許可がない.shファイル
=> fix error msg

Makefile, inc/invoke_cmd/redirect.h, src/invoke_cmd/exec_pipeline.c, src/invoke_cmd/redirect_handler.c
#257 のテストケースは通るようになったので、検証してほしいです。
ちなみに、` echo hello > out > >`のようなコマンドが入力された時は、parserで弾く認識で合っていますか？
=> fix redirect process

src/invoke_cmd/execute_cmd.c
fix #253 
　ft_strchrを追加し、入力されたコマンドに`/`が存在した時、accessでファイルが存在するか検証するようにした。
　カレントディレクトリにコマンド（以降、コマンドをcatとして考える）と同じ名前のファイルがあるときは、get_cmd_pathのaccess(cmd, F_OK)は成功するが、execute_cmdのaccess(fullpath, X_OK)は失敗し、　Permission deniedのエラーメッセージが出力される。
　カレントディレクトリにcatと同じ名前のファイルがないときは、そもそもget_cmd_pathのaccess(cmd, F_OK)の確認には至らず、fullpathが作成される。そして、execute_cmdでcatが実行される。
=> add process that validates command path

src/invoke_cmd/execute_cmd.c
fix #263 
実行権限のないファイルを実行したときのexit statusがbashと一致していなかったので、修正した。原因はexit()を書いておらず、minishのlast statusに渡せていなかったことでした。
実行権限のないファイルを実行して、echo $?で確認できます。
=> fix exit status when file has no permission

inc/tokenizer/tokenizer.h, src/main.c, src/tokenizer/is_redirect_validate.c, src/tokenizer/tokenizer.c
fixed #255 
不正なリダイレクトエラー時にステータスコードを返せていなかったので返すように設定しました。
minishellで`<<<`のような不正なリダイレクトエラーを入力後、`echo $?`でExit Statusに2が入っているかご確認ください。
上記確認でsyntax Errorというメッセージが出ますが、#256のマージで消える予定ですので無視してください。
=> リダイレクトエラー時にminishのlast-statusにセットするように修正

src/builtin/unset.c
fixed #266 
unsetの引数なしの場合、何もせずexit statusを0に設定するように変更しました。
- `minishell`を起動後`unset`コマンドを実行してexit statusが0になっていることをご確認ください。
- unsetの基本的な動作に問題がないことをご確認ください。
=> 引数なしなら何もしないように修正

src/invoke_cmd/invoke_command.c
fix #268 
リダイレクトは３つ以上受け付けられるように修正しました。
./minishellで確認していただけるとありがたいです。
```
$ echo hello < Makefile > out > out2 > out3
$ echo hello < Makefile < README.md > out > out2 > out3
$ echo bye < Makefile < README.md > out > out2 > out3
```
ただ、以下のようにリダイレクト後やリダイレクト間にテキストがあった場合は、処理できないです。
```
$ echo hello < Makefile > out > out2 > out3 bye
$ echo hello < Makefile < README.md hi > out > out2 > out3 hey
```
=> fix redirect
